// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bee struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Info     string `json:"info"`
	ImageURL string `json:"imageURL"`
	WikiURL  string `json:"wikiURL"`
}

type NewBee struct {
	Username string `json:"username"`
	Info     string `json:"info"`
	ImageURL string `json:"imageURL"`
	WikiURL  string `json:"wikiURL"`
}

type NewRequest struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	FullText string `json:"full_text"`
}

type Request struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	FullText string `json:"full_text"`
}

type UpdateBee struct {
	ID       *string `json:"id"`
	Username *string `json:"username"`
	Info     *string `json:"info"`
	ImageURL *string `json:"imageURL"`
	WikiURL  *string `json:"wikiURL"`
}

type RequestFilter struct {
	FullText *string `json:"full_text"`
}
